/* hko_tctrack.js — GENERATED by scripts/ingest_tctrack.py. Do not edit by hand.
 * HKO updates TC forecast tracks 3-hourly (6-hourly for distant systems);
 * this file is refreshed every 30 minutes by Actions, commit-only-on-change.
 * storms: [] means HKO currently issues no forecast track — a real answer.
 * The page shows bulletinTime and generatedAt separately: staleness is
 * always visible, never hidden. */
const HK_TCTRACK = {
  "generatedAt": "2026-09-27T15:38:24+00:00",
  "source": "HKO tc_list.xml + hko_tctrack_{TCID}.xml on www.weather.gov.hk (no CORS headers; ingested every 30 min by GitHub Actions)",
  "storms": [
    {
      "id": "2641",
      "nameEn": "SURIGAE",
      "nameZh": "舒力基",
      "bulletinTime": "2026-09-27T22:00:49+08:00",
      "analysis": {
        "lat": 25.9,
        "lon": 129.1,
        "time": "2026-09-27T12:00:00+00:00",
        "intensity": "Super Typhoon",
        "wind": "220km/h"
      },
      "past": [
        {
          "i": 1,
          "lat": 14.9,
          "lon": 139.9,
          "time": "2026-09-22T18:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 2,
          "lat": 15.7,
          "lon": 138.8,
          "time": "2026-09-23T00:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 3,
          "lat": 16.1,
          "lon": 138.3,
          "time": "2026-09-23T06:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 4,
          "lat": 16.9,
          "lon": 137.3,
          "time": "2026-09-23T12:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "55km/h"
        },
        {
          "i": 5,
          "lat": 17.4,
          "lon": 135.8,
          "time": "2026-09-23T18:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "65km/h"
        },
        {
          "i": 6,
          "lat": 18.1,
          "lon": 134.3,
          "time": "2026-09-24T00:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "75km/h"
        },
        {
          "i": 7,
          "lat": 18.7,
          "lon": 133.1,
          "time": "2026-09-24T06:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "75km/h"
        },
        {
          "i": 8,
          "lat": 19.1,
          "lon": 132.0,
          "time": "2026-09-24T12:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        },
        {
          "i": 9,
          "lat": 19.3,
          "lon": 131.3,
          "time": "2026-09-24T18:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        },
        {
          "i": 10,
          "lat": 19.9,
          "lon": 130.4,
          "time": "2026-09-25T00:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        },
        {
          "i": 11,
          "lat": 20.7,
          "lon": 129.2,
          "time": "2026-09-25T06:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        },
        {
          "i": 12,
          "lat": 21.2,
          "lon": 128.5,
          "time": "2026-09-25T12:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        },
        {
          "i": 13,
          "lat": 21.6,
          "lon": 127.7,
          "time": "2026-09-25T18:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "90km/h"
        },
        {
          "i": 14,
          "lat": 22.2,
          "lon": 127.1,
          "time": "2026-09-26T00:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "105km/h"
        },
        {
          "i": 15,
          "lat": 23.0,
          "lon": 127.1,
          "time": "2026-09-26T06:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "110km/h"
        },
        {
          "i": 16,
          "lat": 23.4,
          "lon": 127.1,
          "time": "2026-09-26T12:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "110km/h"
        },
        {
          "i": 17,
          "lat": 24.0,
          "lon": 127.2,
          "time": "2026-09-26T18:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "130km/h"
        },
        {
          "i": 18,
          "lat": 24.7,
          "lon": 127.6,
          "time": "2026-09-27T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 19,
          "lat": 25.3,
          "lon": 128.2,
          "time": "2026-09-27T06:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "195km/h"
        }
      ],
      "forecast": [
        {
          "i": 1,
          "lat": 25.95,
          "lon": 129.15
        },
        {
          "i": 2,
          "lat": 26.03,
          "lon": 129.21
        },
        {
          "i": 3,
          "lat": 26.12,
          "lon": 129.29
        },
        {
          "i": 4,
          "lat": 26.21,
          "lon": 129.39
        },
        {
          "i": 5,
          "lat": 26.31,
          "lon": 129.49
        },
        {
          "i": 6,
          "lat": 26.4,
          "lon": 129.6
        },
        {
          "i": 7,
          "lat": 26.48,
          "lon": 129.73
        },
        {
          "i": 8,
          "lat": 26.57,
          "lon": 129.87
        },
        {
          "i": 9,
          "lat": 26.65,
          "lon": 130.02
        },
        {
          "i": 10,
          "lat": 26.73,
          "lon": 130.19
        },
        {
          "i": 11,
          "lat": 26.82,
          "lon": 130.35
        },
        {
          "i": 12,
          "lat": 26.9,
          "lon": 130.5
        },
        {
          "i": 13,
          "lat": 26.98,
          "lon": 130.65
        },
        {
          "i": 14,
          "lat": 27.07,
          "lon": 130.8
        },
        {
          "i": 15,
          "lat": 27.16,
          "lon": 130.95
        },
        {
          "i": 16,
          "lat": 27.24,
          "lon": 131.1
        },
        {
          "i": 17,
          "lat": 27.32,
          "lon": 131.25
        },
        {
          "i": 18,
          "lat": 27.4,
          "lon": 131.4
        },
        {
          "i": 19,
          "lat": 27.47,
          "lon": 131.55
        },
        {
          "i": 20,
          "lat": 27.54,
          "lon": 131.7
        },
        {
          "i": 21,
          "lat": 27.61,
          "lon": 131.86
        },
        {
          "i": 22,
          "lat": 27.67,
          "lon": 132.01
        },
        {
          "i": 23,
          "lat": 27.73,
          "lon": 132.16
        },
        {
          "i": 24,
          "lat": 27.8,
          "lon": 132.3,
          "time": "2026-09-28T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 25,
          "lat": 27.87,
          "lon": 132.44
        },
        {
          "i": 26,
          "lat": 27.93,
          "lon": 132.57
        },
        {
          "i": 27,
          "lat": 27.99,
          "lon": 132.7
        },
        {
          "i": 28,
          "lat": 28.06,
          "lon": 132.83
        },
        {
          "i": 29,
          "lat": 28.13,
          "lon": 132.96
        },
        {
          "i": 30,
          "lat": 28.2,
          "lon": 133.1
        },
        {
          "i": 31,
          "lat": 28.28,
          "lon": 133.24
        },
        {
          "i": 32,
          "lat": 28.36,
          "lon": 133.39
        },
        {
          "i": 33,
          "lat": 28.44,
          "lon": 133.53
        },
        {
          "i": 34,
          "lat": 28.53,
          "lon": 133.68
        },
        {
          "i": 35,
          "lat": 28.62,
          "lon": 133.84
        },
        {
          "i": 36,
          "lat": 28.7,
          "lon": 134.0
        },
        {
          "i": 37,
          "lat": 28.79,
          "lon": 134.17
        },
        {
          "i": 38,
          "lat": 28.87,
          "lon": 134.36
        },
        {
          "i": 39,
          "lat": 28.96,
          "lon": 134.54
        },
        {
          "i": 40,
          "lat": 29.05,
          "lon": 134.73
        },
        {
          "i": 41,
          "lat": 29.13,
          "lon": 134.92
        },
        {
          "i": 42,
          "lat": 29.2,
          "lon": 135.1
        },
        {
          "i": 43,
          "lat": 29.26,
          "lon": 135.27
        },
        {
          "i": 44,
          "lat": 29.3,
          "lon": 135.44
        },
        {
          "i": 45,
          "lat": 29.34,
          "lon": 135.6
        },
        {
          "i": 46,
          "lat": 29.38,
          "lon": 135.76
        },
        {
          "i": 47,
          "lat": 29.43,
          "lon": 135.93
        },
        {
          "i": 48,
          "lat": 29.5,
          "lon": 136.1,
          "time": "2026-09-29T12:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "130km/h"
        },
        {
          "i": 49,
          "lat": 29.59,
          "lon": 136.28
        },
        {
          "i": 50,
          "lat": 29.71,
          "lon": 136.46
        },
        {
          "i": 51,
          "lat": 29.83,
          "lon": 136.64
        },
        {
          "i": 52,
          "lat": 29.96,
          "lon": 136.82
        },
        {
          "i": 53,
          "lat": 30.08,
          "lon": 137.01
        },
        {
          "i": 54,
          "lat": 30.2,
          "lon": 137.2
        },
        {
          "i": 55,
          "lat": 30.3,
          "lon": 137.39
        },
        {
          "i": 56,
          "lat": 30.4,
          "lon": 137.59
        },
        {
          "i": 57,
          "lat": 30.5,
          "lon": 137.79
        },
        {
          "i": 58,
          "lat": 30.6,
          "lon": 138.0
        },
        {
          "i": 59,
          "lat": 30.7,
          "lon": 138.2
        },
        {
          "i": 60,
          "lat": 30.8,
          "lon": 138.4
        },
        {
          "i": 61,
          "lat": 30.91,
          "lon": 138.6
        },
        {
          "i": 62,
          "lat": 31.03,
          "lon": 138.8
        },
        {
          "i": 63,
          "lat": 31.15,
          "lon": 139.01
        },
        {
          "i": 64,
          "lat": 31.27,
          "lon": 139.21
        },
        {
          "i": 65,
          "lat": 31.39,
          "lon": 139.41
        },
        {
          "i": 66,
          "lat": 31.5,
          "lon": 139.6
        },
        {
          "i": 67,
          "lat": 31.6,
          "lon": 139.79
        },
        {
          "i": 68,
          "lat": 31.7,
          "lon": 139.98
        },
        {
          "i": 69,
          "lat": 31.79,
          "lon": 140.17
        },
        {
          "i": 70,
          "lat": 31.88,
          "lon": 140.35
        },
        {
          "i": 71,
          "lat": 31.98,
          "lon": 140.53
        },
        {
          "i": 72,
          "lat": 32.1,
          "lon": 140.7,
          "time": "2026-09-30T12:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "105km/h"
        },
        {
          "i": 73,
          "lat": 32.23,
          "lon": 140.86
        },
        {
          "i": 74,
          "lat": 32.38,
          "lon": 141.0
        },
        {
          "i": 75,
          "lat": 32.53,
          "lon": 141.14
        },
        {
          "i": 76,
          "lat": 32.69,
          "lon": 141.28
        },
        {
          "i": 77,
          "lat": 32.85,
          "lon": 141.43
        },
        {
          "i": 78,
          "lat": 33.0,
          "lon": 141.6
        },
        {
          "i": 79,
          "lat": 33.15,
          "lon": 141.79
        },
        {
          "i": 80,
          "lat": 33.29,
          "lon": 142.0
        },
        {
          "i": 81,
          "lat": 33.44,
          "lon": 142.21
        },
        {
          "i": 82,
          "lat": 33.59,
          "lon": 142.44
        },
        {
          "i": 83,
          "lat": 33.74,
          "lon": 142.67
        },
        {
          "i": 84,
          "lat": 33.9,
          "lon": 142.9
        },
        {
          "i": 85,
          "lat": 34.07,
          "lon": 143.13
        },
        {
          "i": 86,
          "lat": 34.23,
          "lon": 143.37
        },
        {
          "i": 87,
          "lat": 34.41,
          "lon": 143.61
        },
        {
          "i": 88,
          "lat": 34.59,
          "lon": 143.86
        },
        {
          "i": 89,
          "lat": 34.79,
          "lon": 144.12
        },
        {
          "i": 90,
          "lat": 35.0,
          "lon": 144.4
        },
        {
          "i": 91,
          "lat": 35.24,
          "lon": 144.71
        },
        {
          "i": 92,
          "lat": 35.51,
          "lon": 145.04
        },
        {
          "i": 93,
          "lat": 35.8,
          "lon": 145.39
        },
        {
          "i": 94,
          "lat": 36.09,
          "lon": 145.74
        },
        {
          "i": 95,
          "lat": 36.36,
          "lon": 146.08
        },
        {
          "i": 96,
          "lat": 36.6,
          "lon": 146.4,
          "time": "2026-10-01T12:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "90km/h"
        },
        {
          "i": 97,
          "lat": 36.81,
          "lon": 146.69
        },
        {
          "i": 98,
          "lat": 37.01,
          "lon": 146.97
        },
        {
          "i": 99,
          "lat": 37.19,
          "lon": 147.23
        },
        {
          "i": 100,
          "lat": 37.37,
          "lon": 147.49
        },
        {
          "i": 101,
          "lat": 37.53,
          "lon": 147.74
        },
        {
          "i": 102,
          "lat": 37.7,
          "lon": 148.0
        },
        {
          "i": 103,
          "lat": 37.87,
          "lon": 148.26
        },
        {
          "i": 104,
          "lat": 38.03,
          "lon": 148.51
        },
        {
          "i": 105,
          "lat": 38.18,
          "lon": 148.77
        },
        {
          "i": 106,
          "lat": 38.33,
          "lon": 149.02
        },
        {
          "i": 107,
          "lat": 38.47,
          "lon": 149.26
        },
        {
          "i": 108,
          "lat": 38.6,
          "lon": 149.5
        },
        {
          "i": 109,
          "lat": 38.72,
          "lon": 149.73
        },
        {
          "i": 110,
          "lat": 38.82,
          "lon": 149.96
        },
        {
          "i": 111,
          "lat": 38.92,
          "lon": 150.18
        },
        {
          "i": 112,
          "lat": 39.01,
          "lon": 150.39
        },
        {
          "i": 113,
          "lat": 39.1,
          "lon": 150.6
        },
        {
          "i": 114,
          "lat": 39.2,
          "lon": 150.8
        },
        {
          "i": 115,
          "lat": 39.31,
          "lon": 151.01
        },
        {
          "i": 116,
          "lat": 39.42,
          "lon": 151.22
        },
        {
          "i": 117,
          "lat": 39.54,
          "lon": 151.43
        },
        {
          "i": 118,
          "lat": 39.64,
          "lon": 151.62
        },
        {
          "i": 119,
          "lat": 39.73,
          "lon": 151.78
        },
        {
          "i": 120,
          "lat": 39.8,
          "lon": 151.9,
          "time": "2026-10-02T12:00:00+00:00",
          "intensity": "Extratropical Low",
          "wind": "--"
        }
      ]
    }
  ]
};
