/* hko_tctrack.js — GENERATED by scripts/ingest_tctrack.py. Do not edit by hand.
 * HKO updates TC forecast tracks 3-hourly (6-hourly for distant systems);
 * this file is refreshed every 30 minutes by Actions, commit-only-on-change.
 * storms: [] means HKO currently issues no forecast track — a real answer.
 * The page shows bulletinTime and generatedAt separately: staleness is
 * always visible, never hidden. */
const HK_TCTRACK = {
  "generatedAt": "2026-08-08T23:13:56+00:00",
  "source": "HKO tc_list.xml + hko_tctrack_{TCID}.xml on www.weather.gov.hk (no CORS headers; ingested every 30 min by GitHub Actions)",
  "storms": [
    {
      "id": "2618",
      "nameEn": "DOLPHIN",
      "nameZh": "白海豚",
      "bulletinTime": "2026-08-09T06:36:11+08:00",
      "analysis": {
        "lat": 27.4,
        "lon": 123.7,
        "time": "2026-08-08T21:00:00+00:00",
        "intensity": "Severe Typhoon",
        "wind": "165km/h"
      },
      "past": [
        {
          "i": 1,
          "lat": 24.0,
          "lon": 149.5,
          "time": "2026-08-02T18:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "185km/h"
        },
        {
          "i": 2,
          "lat": 24.4,
          "lon": 148.5,
          "time": "2026-08-03T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 3,
          "lat": 24.9,
          "lon": 147.1,
          "time": "2026-08-03T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 4,
          "lat": 25.0,
          "lon": 145.6,
          "time": "2026-08-03T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 5,
          "lat": 25.2,
          "lon": 144.2,
          "time": "2026-08-03T18:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 6,
          "lat": 25.2,
          "lon": 143.2,
          "time": "2026-08-04T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 7,
          "lat": 25.2,
          "lon": 141.8,
          "time": "2026-08-04T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 8,
          "lat": 25.2,
          "lon": 140.5,
          "time": "2026-08-04T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 9,
          "lat": 25.3,
          "lon": 140.0,
          "time": "2026-08-04T15:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 10,
          "lat": 25.3,
          "lon": 139.3,
          "time": "2026-08-04T18:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 11,
          "lat": 25.4,
          "lon": 138.3,
          "time": "2026-08-05T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 12,
          "lat": 25.7,
          "lon": 137.3,
          "time": "2026-08-05T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 13,
          "lat": 26.0,
          "lon": 136.2,
          "time": "2026-08-05T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 14,
          "lat": 26.3,
          "lon": 135.1,
          "time": "2026-08-05T18:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 15,
          "lat": 26.3,
          "lon": 133.6,
          "time": "2026-08-06T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 16,
          "lat": 26.6,
          "lon": 132.6,
          "time": "2026-08-06T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 17,
          "lat": 26.5,
          "lon": 131.4,
          "time": "2026-08-06T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 18,
          "lat": 26.9,
          "lon": 130.3,
          "time": "2026-08-06T18:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 19,
          "lat": 27.2,
          "lon": 128.9,
          "time": "2026-08-07T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 20,
          "lat": 26.8,
          "lon": 128.0,
          "time": "2026-08-07T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 21,
          "lat": 27.2,
          "lon": 127.2,
          "time": "2026-08-07T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 22,
          "lat": 26.6,
          "lon": 126.5,
          "time": "2026-08-07T18:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 23,
          "lat": 27.0,
          "lon": 126.1,
          "time": "2026-08-08T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 24,
          "lat": 26.9,
          "lon": 125.2,
          "time": "2026-08-08T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 25,
          "lat": 26.9,
          "lon": 125.0,
          "time": "2026-08-08T09:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 26,
          "lat": 27.0,
          "lon": 124.8,
          "time": "2026-08-08T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 27,
          "lat": 27.1,
          "lon": 124.3,
          "time": "2026-08-08T15:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        },
        {
          "i": 28,
          "lat": 27.1,
          "lon": 124.0,
          "time": "2026-08-08T18:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "165km/h"
        }
      ],
      "forecast": [
        {
          "i": 1,
          "lat": 27.43,
          "lon": 123.59
        },
        {
          "i": 2,
          "lat": 27.47,
          "lon": 123.45
        },
        {
          "i": 3,
          "lat": 27.51,
          "lon": 123.28
        },
        {
          "i": 4,
          "lat": 27.57,
          "lon": 123.09
        },
        {
          "i": 5,
          "lat": 27.62,
          "lon": 122.89
        },
        {
          "i": 6,
          "lat": 27.68,
          "lon": 122.67
        },
        {
          "i": 7,
          "lat": 27.74,
          "lon": 122.45
        },
        {
          "i": 8,
          "lat": 27.8,
          "lon": 122.23
        },
        {
          "i": 9,
          "lat": 27.86,
          "lon": 122.01
        },
        {
          "i": 10,
          "lat": 27.91,
          "lon": 121.79
        },
        {
          "i": 11,
          "lat": 27.96,
          "lon": 121.59
        },
        {
          "i": 12,
          "lat": 28.0,
          "lon": 121.4
        },
        {
          "i": 13,
          "lat": 28.03,
          "lon": 121.22
        },
        {
          "i": 14,
          "lat": 28.05,
          "lon": 121.04
        },
        {
          "i": 15,
          "lat": 28.07,
          "lon": 120.87
        },
        {
          "i": 16,
          "lat": 28.07,
          "lon": 120.7
        },
        {
          "i": 17,
          "lat": 28.08,
          "lon": 120.53
        },
        {
          "i": 18,
          "lat": 28.09,
          "lon": 120.36
        },
        {
          "i": 19,
          "lat": 28.1,
          "lon": 120.19
        },
        {
          "i": 20,
          "lat": 28.11,
          "lon": 120.03
        },
        {
          "i": 21,
          "lat": 28.14,
          "lon": 119.86
        },
        {
          "i": 22,
          "lat": 28.18,
          "lon": 119.71
        },
        {
          "i": 23,
          "lat": 28.23,
          "lon": 119.55
        },
        {
          "i": 24,
          "lat": 28.3,
          "lon": 119.4,
          "time": "2026-08-09T21:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "120km/h"
        },
        {
          "i": 25,
          "lat": 28.39,
          "lon": 119.26
        },
        {
          "i": 26,
          "lat": 28.49,
          "lon": 119.12
        },
        {
          "i": 27,
          "lat": 28.61,
          "lon": 118.99
        },
        {
          "i": 28,
          "lat": 28.74,
          "lon": 118.87
        },
        {
          "i": 29,
          "lat": 28.88,
          "lon": 118.75
        },
        {
          "i": 30,
          "lat": 29.03,
          "lon": 118.62
        },
        {
          "i": 31,
          "lat": 29.18,
          "lon": 118.5
        },
        {
          "i": 32,
          "lat": 29.33,
          "lon": 118.38
        },
        {
          "i": 33,
          "lat": 29.48,
          "lon": 118.25
        },
        {
          "i": 34,
          "lat": 29.63,
          "lon": 118.11
        },
        {
          "i": 35,
          "lat": 29.77,
          "lon": 117.96
        },
        {
          "i": 36,
          "lat": 29.9,
          "lon": 117.8
        },
        {
          "i": 37,
          "lat": 30.03,
          "lon": 117.62
        },
        {
          "i": 38,
          "lat": 30.16,
          "lon": 117.43
        },
        {
          "i": 39,
          "lat": 30.29,
          "lon": 117.23
        },
        {
          "i": 40,
          "lat": 30.42,
          "lon": 117.02
        },
        {
          "i": 41,
          "lat": 30.55,
          "lon": 116.8
        },
        {
          "i": 42,
          "lat": 30.68,
          "lon": 116.58
        },
        {
          "i": 43,
          "lat": 30.8,
          "lon": 116.36
        },
        {
          "i": 44,
          "lat": 30.92,
          "lon": 116.15
        },
        {
          "i": 45,
          "lat": 31.03,
          "lon": 115.94
        },
        {
          "i": 46,
          "lat": 31.13,
          "lon": 115.75
        },
        {
          "i": 47,
          "lat": 31.22,
          "lon": 115.56
        },
        {
          "i": 48,
          "lat": 31.3,
          "lon": 115.4,
          "time": "2026-08-10T21:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "65km/h"
        },
        {
          "i": 49,
          "lat": 31.36,
          "lon": 115.25
        },
        {
          "i": 50,
          "lat": 31.41,
          "lon": 115.11
        },
        {
          "i": 51,
          "lat": 31.44,
          "lon": 114.97
        },
        {
          "i": 52,
          "lat": 31.47,
          "lon": 114.85
        },
        {
          "i": 53,
          "lat": 31.48,
          "lon": 114.73
        },
        {
          "i": 54,
          "lat": 31.49,
          "lon": 114.62
        },
        {
          "i": 55,
          "lat": 31.5,
          "lon": 114.52
        },
        {
          "i": 56,
          "lat": 31.51,
          "lon": 114.42
        },
        {
          "i": 57,
          "lat": 31.52,
          "lon": 114.33
        },
        {
          "i": 58,
          "lat": 31.54,
          "lon": 114.25
        },
        {
          "i": 59,
          "lat": 31.56,
          "lon": 114.17
        },
        {
          "i": 60,
          "lat": 31.6,
          "lon": 114.1
        },
        {
          "i": 61,
          "lat": 31.65,
          "lon": 114.04
        },
        {
          "i": 62,
          "lat": 31.7,
          "lon": 113.98
        },
        {
          "i": 63,
          "lat": 31.76,
          "lon": 113.94
        },
        {
          "i": 64,
          "lat": 31.82,
          "lon": 113.9
        },
        {
          "i": 65,
          "lat": 31.88,
          "lon": 113.87
        },
        {
          "i": 66,
          "lat": 31.95,
          "lon": 113.84
        },
        {
          "i": 67,
          "lat": 32.02,
          "lon": 113.82
        },
        {
          "i": 68,
          "lat": 32.08,
          "lon": 113.81
        },
        {
          "i": 69,
          "lat": 32.14,
          "lon": 113.8
        },
        {
          "i": 70,
          "lat": 32.2,
          "lon": 113.8
        },
        {
          "i": 71,
          "lat": 32.25,
          "lon": 113.8
        },
        {
          "i": 72,
          "lat": 32.3,
          "lon": 113.8,
          "time": "2026-08-11T21:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 73,
          "lat": 32.34,
          "lon": 113.81
        },
        {
          "i": 74,
          "lat": 32.37,
          "lon": 113.83
        },
        {
          "i": 75,
          "lat": 32.41,
          "lon": 113.85
        },
        {
          "i": 76,
          "lat": 32.43,
          "lon": 113.88
        },
        {
          "i": 77,
          "lat": 32.46,
          "lon": 113.92
        },
        {
          "i": 78,
          "lat": 32.48,
          "lon": 113.96
        },
        {
          "i": 79,
          "lat": 32.5,
          "lon": 114.0
        },
        {
          "i": 80,
          "lat": 32.52,
          "lon": 114.04
        },
        {
          "i": 81,
          "lat": 32.54,
          "lon": 114.08
        },
        {
          "i": 82,
          "lat": 32.56,
          "lon": 114.13
        },
        {
          "i": 83,
          "lat": 32.58,
          "lon": 114.16
        },
        {
          "i": 84,
          "lat": 32.6,
          "lon": 114.2
        },
        {
          "i": 85,
          "lat": 32.62,
          "lon": 114.23
        },
        {
          "i": 86,
          "lat": 32.64,
          "lon": 114.27
        },
        {
          "i": 87,
          "lat": 32.66,
          "lon": 114.31
        },
        {
          "i": 88,
          "lat": 32.68,
          "lon": 114.35
        },
        {
          "i": 89,
          "lat": 32.7,
          "lon": 114.39
        },
        {
          "i": 90,
          "lat": 32.72,
          "lon": 114.43
        },
        {
          "i": 91,
          "lat": 32.74,
          "lon": 114.46
        },
        {
          "i": 92,
          "lat": 32.75,
          "lon": 114.5
        },
        {
          "i": 93,
          "lat": 32.77,
          "lon": 114.53
        },
        {
          "i": 94,
          "lat": 32.78,
          "lon": 114.56
        },
        {
          "i": 95,
          "lat": 32.79,
          "lon": 114.58
        },
        {
          "i": 96,
          "lat": 32.8,
          "lon": 114.6,
          "time": "2026-08-12T21:00:00+00:00",
          "intensity": "Low Pressure Area",
          "wind": "40km/h"
        }
      ]
    },
    {
      "id": "2622",
      "nameEn": "Low Pressure Area",
      "nameZh": "低壓區",
      "bulletinTime": "2026-08-08T15:30:27+08:00",
      "analysis": {
        "lat": 19.5,
        "lon": 109.3,
        "time": "2026-08-08T06:00:00+00:00",
        "intensity": "Low Pressure Area",
        "wind": "40km/h"
      },
      "past": [
        {
          "i": 1,
          "lat": 19.9,
          "lon": 108.6,
          "time": "2026-08-07T18:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 2,
          "lat": 19.8,
          "lon": 108.8,
          "time": "2026-08-07T21:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 3,
          "lat": 19.7,
          "lon": 108.9,
          "time": "2026-08-08T00:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 4,
          "lat": 19.6,
          "lon": 109.0,
          "time": "2026-08-08T03:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        }
      ],
      "forecast": []
    }
  ]
};
