/* hko_tctrack.js — GENERATED by scripts/ingest_tctrack.py. Do not edit by hand.
 * HKO updates TC forecast tracks 3-hourly (6-hourly for distant systems);
 * this file is refreshed every 30 minutes by Actions, commit-only-on-change.
 * storms: [] means HKO currently issues no forecast track — a real answer.
 * The page shows bulletinTime and generatedAt separately: staleness is
 * always visible, never hidden. */
const HK_TCTRACK = {
  "generatedAt": "2026-09-29T23:11:06+00:00",
  "source": "HKO tc_list.xml + hko_tctrack_{TCID}.xml on www.weather.gov.hk (no CORS headers; ingested every 30 min by GitHub Actions)",
  "storms": [
    {
      "id": "2641",
      "nameEn": "SURIGAE",
      "nameZh": "舒力基",
      "bulletinTime": "2026-09-30T04:00:48+08:00",
      "analysis": {
        "lat": 29.6,
        "lon": 136.7,
        "time": "2026-09-29T18:00:00+00:00",
        "intensity": "Tropical Storm",
        "wind": "75km/h"
      },
      "past": [
        {
          "i": 1,
          "lat": 14.9,
          "lon": 139.9,
          "time": "2026-09-22T18:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 2,
          "lat": 15.7,
          "lon": 138.8,
          "time": "2026-09-23T00:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 3,
          "lat": 16.1,
          "lon": 138.3,
          "time": "2026-09-23T06:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "45km/h"
        },
        {
          "i": 4,
          "lat": 16.9,
          "lon": 137.3,
          "time": "2026-09-23T12:00:00+00:00",
          "intensity": "Tropical Depression",
          "wind": "55km/h"
        },
        {
          "i": 5,
          "lat": 17.4,
          "lon": 135.8,
          "time": "2026-09-23T18:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "65km/h"
        },
        {
          "i": 6,
          "lat": 18.1,
          "lon": 134.3,
          "time": "2026-09-24T00:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "75km/h"
        },
        {
          "i": 7,
          "lat": 18.7,
          "lon": 133.1,
          "time": "2026-09-24T06:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "75km/h"
        },
        {
          "i": 8,
          "lat": 19.1,
          "lon": 132.0,
          "time": "2026-09-24T12:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        },
        {
          "i": 9,
          "lat": 19.3,
          "lon": 131.3,
          "time": "2026-09-24T18:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        },
        {
          "i": 10,
          "lat": 19.9,
          "lon": 130.4,
          "time": "2026-09-25T00:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        },
        {
          "i": 11,
          "lat": 20.7,
          "lon": 129.2,
          "time": "2026-09-25T06:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        },
        {
          "i": 12,
          "lat": 21.2,
          "lon": 128.5,
          "time": "2026-09-25T12:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        },
        {
          "i": 13,
          "lat": 21.6,
          "lon": 127.7,
          "time": "2026-09-25T18:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "90km/h"
        },
        {
          "i": 14,
          "lat": 22.2,
          "lon": 127.1,
          "time": "2026-09-26T00:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "105km/h"
        },
        {
          "i": 15,
          "lat": 23.0,
          "lon": 127.1,
          "time": "2026-09-26T06:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "110km/h"
        },
        {
          "i": 16,
          "lat": 23.4,
          "lon": 127.1,
          "time": "2026-09-26T12:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "110km/h"
        },
        {
          "i": 17,
          "lat": 24.0,
          "lon": 127.2,
          "time": "2026-09-26T18:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "130km/h"
        },
        {
          "i": 18,
          "lat": 24.7,
          "lon": 127.6,
          "time": "2026-09-27T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 19,
          "lat": 25.3,
          "lon": 128.2,
          "time": "2026-09-27T06:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "195km/h"
        },
        {
          "i": 20,
          "lat": 25.9,
          "lon": 129.1,
          "time": "2026-09-27T12:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "220km/h"
        },
        {
          "i": 21,
          "lat": 26.4,
          "lon": 130.0,
          "time": "2026-09-27T18:00:00+00:00",
          "intensity": "Super Typhoon",
          "wind": "220km/h"
        },
        {
          "i": 22,
          "lat": 26.6,
          "lon": 130.9,
          "time": "2026-09-28T00:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 23,
          "lat": 27.1,
          "lon": 131.9,
          "time": "2026-09-28T06:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "175km/h"
        },
        {
          "i": 24,
          "lat": 27.6,
          "lon": 132.6,
          "time": "2026-09-28T12:00:00+00:00",
          "intensity": "Severe Typhoon",
          "wind": "155km/h"
        },
        {
          "i": 25,
          "lat": 27.7,
          "lon": 133.3,
          "time": "2026-09-28T18:00:00+00:00",
          "intensity": "Typhoon",
          "wind": "120km/h"
        },
        {
          "i": 26,
          "lat": 28.4,
          "lon": 134.0,
          "time": "2026-09-29T00:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "105km/h"
        },
        {
          "i": 27,
          "lat": 29.0,
          "lon": 135.1,
          "time": "2026-09-29T06:00:00+00:00",
          "intensity": "Severe Tropical Storm",
          "wind": "90km/h"
        },
        {
          "i": 28,
          "lat": 29.4,
          "lon": 136.0,
          "time": "2026-09-29T12:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "85km/h"
        }
      ],
      "forecast": [
        {
          "i": 1,
          "lat": 29.69,
          "lon": 136.81
        },
        {
          "i": 2,
          "lat": 29.81,
          "lon": 136.96
        },
        {
          "i": 3,
          "lat": 29.95,
          "lon": 137.14
        },
        {
          "i": 4,
          "lat": 30.1,
          "lon": 137.34
        },
        {
          "i": 5,
          "lat": 30.26,
          "lon": 137.53
        },
        {
          "i": 6,
          "lat": 30.4,
          "lon": 137.7
        },
        {
          "i": 7,
          "lat": 30.53,
          "lon": 137.86
        },
        {
          "i": 8,
          "lat": 30.66,
          "lon": 138.01
        },
        {
          "i": 9,
          "lat": 30.79,
          "lon": 138.16
        },
        {
          "i": 10,
          "lat": 30.93,
          "lon": 138.3
        },
        {
          "i": 11,
          "lat": 31.06,
          "lon": 138.45
        },
        {
          "i": 12,
          "lat": 31.2,
          "lon": 138.6
        },
        {
          "i": 13,
          "lat": 31.35,
          "lon": 138.75
        },
        {
          "i": 14,
          "lat": 31.5,
          "lon": 138.9
        },
        {
          "i": 15,
          "lat": 31.65,
          "lon": 139.05
        },
        {
          "i": 16,
          "lat": 31.8,
          "lon": 139.2
        },
        {
          "i": 17,
          "lat": 31.95,
          "lon": 139.35
        },
        {
          "i": 18,
          "lat": 32.1,
          "lon": 139.5
        },
        {
          "i": 19,
          "lat": 32.24,
          "lon": 139.65
        },
        {
          "i": 20,
          "lat": 32.37,
          "lon": 139.79
        },
        {
          "i": 21,
          "lat": 32.49,
          "lon": 139.93
        },
        {
          "i": 22,
          "lat": 32.62,
          "lon": 140.08
        },
        {
          "i": 23,
          "lat": 32.76,
          "lon": 140.23
        },
        {
          "i": 24,
          "lat": 32.9,
          "lon": 140.4,
          "time": "2026-09-30T18:00:00+00:00",
          "intensity": "Tropical Storm",
          "wind": "65km/h"
        },
        {
          "i": 25,
          "lat": 33.05,
          "lon": 140.58
        },
        {
          "i": 26,
          "lat": 33.21,
          "lon": 140.76
        },
        {
          "i": 27,
          "lat": 33.37,
          "lon": 140.96
        },
        {
          "i": 28,
          "lat": 33.54,
          "lon": 141.16
        },
        {
          "i": 29,
          "lat": 33.71,
          "lon": 141.37
        },
        {
          "i": 30,
          "lat": 33.9,
          "lon": 141.6
        },
        {
          "i": 31,
          "lat": 34.11,
          "lon": 141.86
        },
        {
          "i": 32,
          "lat": 34.36,
          "lon": 142.16
        },
        {
          "i": 33,
          "lat": 34.61,
          "lon": 142.47
        },
        {
          "i": 34,
          "lat": 34.85,
          "lon": 142.77
        },
        {
          "i": 35,
          "lat": 35.06,
          "lon": 143.02
        },
        {
          "i": 36,
          "lat": 35.2,
          "lon": 143.2,
          "time": "2026-10-01T06:00:00+00:00",
          "intensity": "Extratropical Low",
          "wind": "--"
        }
      ]
    }
  ]
};
