#!/usr/bin/env python3
"""Generate jma_typhoon_history.js from JMA RSMC Tokyo best-track data.

Sources (official, free):
  - bst_all.zip  : finalized best tracks, all storms since 1951
  - bst<YYYY>.txt: provisional current-season tracks (analysis not yet final)

Finalized data wins when a storm appears in both. Provisional storms are
flagged prov:1 so the UI can label them honestly.

Format reference: https://www.jma.go.jp/jma/jma-eng/jma-center/rsmc-hp-pub-eg/Besttracks/e_format_bst.html
Fixed-width columns are sliced, never whitespace-split (old storms have
blank name fields which would shift token positions).

Output entry per storm:
  {id, n(name, "" if unnamed), y(year), mo:[months active], sd, ed,
   minP(hPa), maxW(kt, 0 before 1977 when winds weren't analysed),
   prov(1 if provisional), t:[[lat*10, lon*10], ...]}

Usage: python3 scripts/ingest_typhoon_history.py [output_path]
"""
import io, json, re, sys, urllib.request, zipfile
from datetime import date, datetime, timezone

BASE = "https://www.jma.go.jp/jma/jma-eng/jma-center/rsmc-hp-pub-eg/Besttracks/"

def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "japan-weather-atlas-ingest"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()

def parse_bst(text, provisional=False):
    storms, cur = [], None
    for raw in text.splitlines():
        line = raw.rstrip("\r\n")
        if not line.strip():
            continue
        if line.startswith("66666"):
            if cur and cur["t"]:
                storms.append(cur)
            intl = line[6:10].strip()
            name = line[30:50].strip()
            if re.fullmatch(r"[-_ ]*", name):
                name = ""
            yy = int(intl[:2])
            year = 1900 + yy if yy >= 51 else 2000 + yy
            cur = {"id": intl, "n": name.title(), "y": year, "mo": set(),
                   "sd": None, "ed": None, "minP": None, "maxW": 0,
                   "prov": 1 if provisional else 0, "t": []}
        elif cur is not None:
            try:
                yy, mm, dd, hh = int(line[0:2]), int(line[2:4]), int(line[4:6]), int(line[6:8])
                lat = int(line[15:18])            # tenths of a degree N
                lon = int(line[19:23])            # tenths of a degree E
                pres = int(line[24:28])
            except ValueError:
                continue                            # malformed fix — skip
            wind = 0
            w = line[33:36].strip()
            if w.isdigit():
                wind = int(w)
            fy = 1900 + yy if yy >= 51 else 2000 + yy
            stamp = f"{fy:04d}-{mm:02d}-{dd:02d}"
            cur["mo"].add(mm)
            if cur["sd"] is None:
                cur["sd"] = stamp
            cur["ed"] = stamp
            if pres and (cur["minP"] is None or pres < cur["minP"]):
                cur["minP"] = pres
            if wind > cur["maxW"]:
                cur["maxW"] = wind
            cur["t"].append([lat, lon])
    if cur and cur["t"]:
        storms.append(cur)
    return storms

def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "jma_typhoon_history.js"

    print("downloading finalized archive (bst_all.zip)…")
    z = zipfile.ZipFile(io.BytesIO(fetch(BASE + "bst_all.zip")))
    final_txt = z.read(z.namelist()[0]).decode("ascii", "replace")
    storms = parse_bst(final_txt)
    have = {s["id"] for s in storms}
    print(f"  finalized storms: {len(storms)} ({storms[0]['y']}–{storms[-1]['y']})")

    # provisional current + previous season (previous may not be finalized yet)
    this_year = date.today().year
    for y in (this_year - 1, this_year):
        url = f"{BASE}bst{y}.txt"
        try:
            prov = parse_bst(fetch(url).decode("ascii", "replace"), provisional=True)
        except Exception:
            continue
        added = [s for s in prov if s["id"] not in have]
        for s in added:
            have.add(s["id"])
        storms += added
        print(f"  provisional bst{y}.txt: {len(prov)} storms, {len(added)} not yet finalized -> added")

    storms.sort(key=lambda s: (s["y"], s["id"]))
    for s in storms:
        s["mo"] = sorted(s["mo"])
        if s["minP"] is None:
            s["minP"] = 0

    fixes = sum(len(s["t"]) for s in storms)
    payload = {
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "source": "JMA RSMC Tokyo best track (bst_all.zip + provisional season files)",
        "storms": storms,
    }
    js = ("/* Generated by scripts/ingest_typhoon_history.py — do not edit by hand.\n"
          "   Historical typhoon best tracks, JMA RSMC Tokyo, 1951–present.        */\n"
          "const JMA_TYPHOON_HISTORY = "
          + json.dumps(payload, separators=(",", ":"), ensure_ascii=False) + ";\n")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"wrote {out_path}: {len(storms)} storms, {fixes} track points, {len(js)/1e6:.2f} MB")

if __name__ == "__main__":
    main()
