/* Generated by scripts/ingest_early_warning.py — do not edit by hand.
   警戒レベル1 早期注意情報（警報級の可能性）.
   A FORECAST OF POSSIBILITY, not an observation and not a warning:
   JMA is saying it may issue a 警報 in the stated window. */
const JMA_EARLY = {
 "areas": {
  "070020": {
   "kinds": [
    {
     "el": "wave",
     "en": "High waves",
     "hits": [
      {
       "at": "2026-10-06T12:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "６日１２時から２４時"
      }
     ],
     "jp": "波",
     "unknown": false
    }
   ],
   "name": "浜通り",
   "office": "福島地方気象台",
   "report": "2026-10-04T05:00:00+09:00",
   "text": "浜通りでは、６日までの期間内に、波浪警報を発表する可能性がある。",
   "worst": "中"
  },
  "080010": {
   "kinds": [
    {
     "el": "wave",
     "en": "High waves",
     "hits": [
      {
       "at": "2026-10-06T12:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "６日１２時から２４時"
      }
     ],
     "jp": "波",
     "unknown": false
    }
   ],
   "name": "北部",
   "office": "水戸地方気象台",
   "report": "2026-10-04T05:00:00+09:00",
   "text": "北部では、６日までの期間内に、波浪警報を発表する可能性がある。",
   "worst": "中"
  },
  "080020": {
   "kinds": [
    {
     "el": "wave",
     "en": "High waves",
     "hits": [
      {
       "at": "2026-10-06T12:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "６日１２時から２４時"
      }
     ],
     "jp": "波",
     "unknown": false
    }
   ],
   "name": "南部",
   "office": "水戸地方気象台",
   "report": "2026-10-04T05:00:00+09:00",
   "text": "南部では、６日までの期間内に、波浪警報を発表する可能性がある。",
   "worst": "中"
  },
  "120020": {
   "kinds": [
    {
     "el": "wave",
     "en": "High waves",
     "hits": [
      {
       "at": "2026-10-06T12:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "６日１２時から２４時"
      }
     ],
     "jp": "波",
     "unknown": false
    }
   ],
   "name": "北東部",
   "office": "銚子地方気象台",
   "report": "2026-10-04T05:00:00+09:00",
   "text": "北東部では、６日までの期間内に、波浪警報を発表する可能性がある。",
   "worst": "中"
  },
  "120030": {
   "kinds": [
    {
     "el": "wave",
     "en": "High waves",
     "hits": [
      {
       "at": "2026-10-06T12:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "６日１２時から２４時"
      }
     ],
     "jp": "波",
     "unknown": false
    }
   ],
   "name": "南部",
   "office": "銚子地方気象台",
   "report": "2026-10-04T05:00:00+09:00",
   "text": "南部では、６日までの期間内に、波浪警報を発表する可能性がある。",
   "worst": "中"
  },
  "130020": {
   "kinds": [
    {
     "el": "wave",
     "en": "High waves",
     "hits": [
      {
       "at": "2026-10-06T12:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "６日１２時から２４時"
      }
     ],
     "jp": "波",
     "unknown": false
    }
   ],
   "name": "伊豆諸島北部",
   "office": "気象庁",
   "report": "2026-10-04T05:00:00+09:00",
   "text": "伊豆諸島北部では、６日までの期間内に、波浪警報を発表する可能性がある。",
   "worst": "中"
  },
  "130030": {
   "kinds": [
    {
     "el": "wave",
     "en": "High waves",
     "hits": [
      {
       "at": "2026-10-06T00:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "６日００時から１２時"
      },
      {
       "at": "2026-10-06T12:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "６日１２時から２４時"
      }
     ],
     "jp": "波",
     "unknown": false
    }
   ],
   "name": "伊豆諸島南部",
   "office": "気象庁",
   "report": "2026-10-04T05:00:00+09:00",
   "text": "伊豆諸島南部では、６日までの期間内に、波浪警報を発表する可能性がある。",
   "worst": "中"
  },
  "130040": {
   "kinds": [
    {
     "el": "landslide",
     "en": "Landslide",
     "hits": [
      {
       "at": "2026-10-06T00:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "６日００時から１２時"
      }
     ],
     "jp": "土砂災害",
     "unknown": false
    },
    {
     "el": "wind",
     "en": "Wind / snowstorm",
     "hits": [
      {
       "at": "2026-10-05T12:00:00+09:00",
       "dur": "PT6H",
       "rank": "中",
       "when": "５日１２時から１８時"
      },
      {
       "at": "2026-10-05T18:00:00+09:00",
       "dur": "PT6H",
       "rank": "中",
       "when": "５日１８時から２４時"
      },
      {
       "at": "2026-10-06T00:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "６日００時から１２時"
      }
     ],
     "jp": "風（風雪）",
     "unknown": false
    },
    {
     "el": "wave",
     "en": "High waves",
     "hits": [
      {
       "at": "2026-10-04T12:00:00+09:00",
       "dur": "PT6H",
       "rank": "中",
       "when": "４日１２時から１８時"
      },
      {
       "at": "2026-10-04T18:00:00+09:00",
       "dur": "PT6H",
       "rank": "高",
       "when": "４日１８時から２４時"
      },
      {
       "at": "2026-10-05T00:00:00+09:00",
       "dur": "PT6H",
       "rank": "高",
       "when": "５日００時から０６時"
      },
      {
       "at": "2026-10-05T06:00:00+09:00",
       "dur": "PT6H",
       "rank": "高",
       "when": "５日０６時から１２時"
      },
      {
       "at": "2026-10-05T12:00:00+09:00",
       "dur": "PT6H",
       "rank": "高",
       "when": "５日１２時から１８時"
      },
      {
       "at": "2026-10-05T18:00:00+09:00",
       "dur": "PT6H",
       "rank": "高",
       "when": "５日１８時から２４時"
      },
      {
       "at": "2026-10-06T00:00:00+09:00",
       "dur": "PT12H",
       "rank": "高",
       "when": "６日００時から１２時"
      },
      {
       "at": "2026-10-06T12:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "６日１２時から２４時"
      }
     ],
     "jp": "波",
     "unknown": false
    }
   ],
   "name": "小笠原諸島",
   "office": "気象庁",
   "report": "2026-10-04T05:00:00+09:00",
   "text": "小笠原諸島では、６日までの期間内に、波浪警報を発表する可能性が高い。また、６日昼前までの期間内に、土砂災害、暴風警報を発表する可能性がある。",
   "worst": "高"
  }
 },
 "generatedAt": "2026-10-03T21:46:32+00:00",
 "offices": 56,
 "officesFailed": 0,
 "product": "早期注意情報（明後日まで）",
 "reportDatetime": "2026-10-04T05:00:00+09:00"
};
