/* Generated by scripts/ingest_early_warning.py — do not edit by hand.
   警戒レベル1 早期注意情報（警報級の可能性）.
   A FORECAST OF POSSIBILITY, not an observation and not a warning:
   JMA is saying it may issue a 警報 in the stated window. */
const JMA_EARLY = {
 "areas": {
  "150040": {
   "kinds": [
    {
     "el": "rain",
     "en": "Heavy rain",
     "hits": [
      {
       "at": "2026-09-14T00:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "１４日００時から１２時"
      },
      {
       "at": "2026-09-14T12:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "１４日１２時から２４時"
      }
     ],
     "jp": "大雨",
     "unknown": false
    }
   ],
   "name": "佐渡",
   "office": "新潟地方気象台",
   "report": "2026-09-12T17:00:00+09:00",
   "text": "佐渡では、１４日までの期間内に、大雨警報を発表する可能性がある。",
   "worst": "中"
  },
  "170010": {
   "kinds": [
    {
     "el": "rain",
     "en": "Heavy rain",
     "hits": [
      {
       "at": "2026-09-14T00:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "１４日００時から１２時"
      },
      {
       "at": "2026-09-14T12:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "１４日１２時から２４時"
      }
     ],
     "jp": "大雨",
     "unknown": false
    }
   ],
   "name": "加賀",
   "office": "金沢地方気象台",
   "report": "2026-09-12T17:00:00+09:00",
   "text": "加賀では、１４日までの期間内に、大雨警報を発表する可能性がある。",
   "worst": "中"
  },
  "170020": {
   "kinds": [
    {
     "el": "rain",
     "en": "Heavy rain",
     "hits": [
      {
       "at": "2026-09-14T00:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "１４日００時から１２時"
      },
      {
       "at": "2026-09-14T12:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "１４日１２時から２４時"
      }
     ],
     "jp": "大雨",
     "unknown": false
    },
    {
     "el": "landslide",
     "en": "Landslide",
     "hits": [
      {
       "at": "2026-09-14T00:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "１４日００時から１２時"
      },
      {
       "at": "2026-09-14T12:00:00+09:00",
       "dur": "PT12H",
       "rank": "中",
       "when": "１４日１２時から２４時"
      }
     ],
     "jp": "土砂災害",
     "unknown": false
    }
   ],
   "name": "能登",
   "office": "金沢地方気象台",
   "report": "2026-09-12T17:00:00+09:00",
   "text": "能登では、１４日までの期間内に、大雨、土砂災害警報を発表する可能性がある。",
   "worst": "中"
  },
  "190020": {
   "kinds": [
    {
     "el": "landslide",
     "en": "Landslide",
     "hits": [
      {
       "at": "2026-09-13T12:00:00+09:00",
       "dur": "PT6H",
       "rank": "中",
       "when": "１３日１２時から１８時"
      },
      {
       "at": "2026-09-13T18:00:00+09:00",
       "dur": "PT6H",
       "rank": "中",
       "when": "１３日１８時から２４時"
      }
     ],
     "jp": "土砂災害",
     "unknown": false
    }
   ],
   "name": "東部・富士五湖",
   "office": "甲府地方気象台",
   "report": "2026-09-12T17:00:00+09:00",
   "text": "東部・富士五湖では、１３日までの期間内に、土砂災害警報を発表する可能性がある。",
   "worst": "中"
  },
  "210010": {
   "kinds": [
    {
     "el": "rain",
     "en": "Heavy rain",
     "hits": [
      {
       "at": "2026-09-13T12:00:00+09:00",
       "dur": "PT6H",
       "rank": "中",
       "when": "１３日１２時から１８時"
      },
      {
       "at": "2026-09-13T18:00:00+09:00",
       "dur": "PT6H",
       "rank": "中",
       "when": "１３日１８時から２４時"
      }
     ],
     "jp": "大雨",
     "unknown": false
    }
   ],
   "name": "美濃地方",
   "office": "岐阜地方気象台",
   "report": "2026-09-12T17:00:00+09:00",
   "text": "美濃地方では、１３日までの期間内に、大雨警報を発表する可能性がある。",
   "worst": "中"
  },
  "240020": {
   "kinds": [
    {
     "el": "rain",
     "en": "Heavy rain",
     "hits": [
      {
       "at": "2026-09-13T00:00:00+09:00",
       "dur": "PT6H",
       "rank": "中",
       "when": "１３日００時から０６時"
      },
      {
       "at": "2026-09-13T06:00:00+09:00",
       "dur": "PT6H",
       "rank": "中",
       "when": "１３日０６時から１２時"
      }
     ],
     "jp": "大雨",
     "unknown": false
    },
    {
     "el": "landslide",
     "en": "Landslide",
     "hits": [
      {
       "at": "2026-09-13T00:00:00+09:00",
       "dur": "PT6H",
       "rank": "中",
       "when": "１３日００時から０６時"
      },
      {
       "at": "2026-09-13T06:00:00+09:00",
       "dur": "PT6H",
       "rank": "中",
       "when": "１３日０６時から１２時"
      }
     ],
     "jp": "土砂災害",
     "unknown": false
    }
   ],
   "name": "南部",
   "office": "津地方気象台",
   "report": "2026-09-12T17:00:00+09:00",
   "text": "南部では、１３日昼前までの期間内に、大雨、土砂災害警報を発表する可能性がある。",
   "worst": "中"
  }
 },
 "generatedAt": "2026-09-12T11:14:37+00:00",
 "offices": 56,
 "officesFailed": 0,
 "product": "早期注意情報（明後日まで）",
 "reportDatetime": "2026-09-12T17:00:00+09:00"
};
