/* Generated by scripts/ingest_nankai.py — do not edit by hand. */
const JMA_NANKAI = {
 "status": "none",
 "keyword": null,
 "headline": null,
 "reportTime": null,
 "telegramUrl": null,
 "latchedSince": null,
 "lastKaisetsu": null,
 "generated": "2026-07-29T19:34:28+09:00",
 "source": "JMA 防災情報XML developer feed (eqvol_l.xml) — latched by GitHub Actions; status persists past the 7-day feed window until an ending telegram is seen"
};
